name: ryanaker
favicon: null
layout_spectrum: 0.5952751652803272
typography_spectrum: 0.3570910661946982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20177974249236286
  lightness: 0.9873775404412299
  saturation: 0.190103244734928
  rhythmicContrast: 0.8628659106325358
purpose: []
